const appname = "eMart";
const appversion = "Version 1.0.0";
const credits = "@Baaba Devs";
const email = "Email";
const emailHint = "admin@admin.com";
const password = "Password";
const passwordHint = "******";
const retypePassword = "Retype Password";
const name = "Name";
const nameHint = "Ali Dev";
const forgetPass = "Forget Password ";
const login = "Log in";
const signup = "Sign up";
const createNewAccount = " or,create a new account";
const loginwith = "Log in with";
const privecyPolicy = "Privacy Policy";
const termAndCond = "Terms adn Conditions";
const alreadyHaveAcoount = "Already Have an Account? ";
const home = "Home",
    categories = "Categories",
    cart = "Cart",
    account = " Account";

const searchanything = "Search Anything...",
    todaydeal = "Today's Deal",
    flashsale = "Flash Sale",
    topSellers = "Top Sellers",
    brand = "Brad",
    topCategories = "Top Categories",
    womendress = "women Clothing",
    girlsWatches = "Girls Watches",
    mobilePhone = "Mobile Phone",
    boysGlasses = "Boys Glasses",
    tShirts = "T Shirts",
    girlsDress = "Girls Dresses",
    featuredProduct = "Featured Producr",
    featuredCategories = "Featured Categories";

const womenClothing = "women Clothing",
    menClothingFashion = "Men Clothing & Fashion",
    compAccess = "Computer & Accessoriies",
    autoMobile = "Automobile",
    kidToys = "kids & Toys",
    sports = "Sports",
    jewelerry = "Jewellery",
    cellPhone = "Cellphone & Tab",
    furniture = "Furniture";
